trigger:
  - main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore ./StringLibrary/StringLibrary.csproj
  displayName: 'Restore StringLibrary'

- script: dotnet build ./StringLibrary/StringLibrary.csproj --configuration $(buildConfiguration)
  displayName: 'Build StringLibrary'

- script: dotnet pack ./StringLibrary/StringLibrary.csproj --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Pack StringLibrary NuGet package'

- script: |
    for %%F in ($(Build.ArtifactStagingDirectory)\*.nupkg) do (
      dotnet nuget push "%%F" --source "https://pkgs.dev.azure.com/cperalt4/_packaging/cperalt4/nuget/v3/index.json" --api-key AzureDevOps --skip-duplicate
    )
  displayName: 'Push StringLibrary NuGet package to Azure Artifacts'
