# Starter pipeline
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'

  - script: dotnet restore
    displayName: 'Restore packages'

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'Build project'

  - script: dotnet pack --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
    displayName: 'Pack NuGet package'

  # Push NuGet package directly to feed URL instead of relying on a named source
  - script: |
      dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg \
        --source "https://pkgs.dev.azure.com/cperalt4/_packaging/cperalt4/nuget/v3/index.json" \
        --api-key AzureDevOps \
        --skip-duplicate
    displayName: 'Push NuGet package to Azure Artifacts'
    env:
      NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED: true
      VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials":[{"endpoint":"https://pkgs.dev.azure.com/cperalt4/_packaging/cperalt4/nuget/v3/index.json","username":"anything","password":"$(System.AccessToken)"}]}'
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
